name: Deploy Lab3 CI/CD

on:
  push:
    branches:
      - master
      - feature

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: echo "Linting HTML... Success!"

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: echo "Building Web... Success!"

  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy
        run: echo "Deploying Pages... Success!"

  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker push
        run: echo "Pushing Docker Image... Success!"
