name: Deploy Lab3 CI/CD

on:
  push:
    branches:
      - master
      - feature

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HTML Hint Lint
        run: |
          echo "Linting HTML file..."
          if grep -q "</html>" index.html; then
            echo "HTML е валиден!"
          else
            echo "Грешка: Недостасува затворачки таг!"
            exit 1
          fi

  build-web:
    needs: lint-html
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy-pages:
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
